---
abstract: 'Payment Processing Library'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-Payment
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  Math::Currency: 0.46
  Moose: 0.87
  MooseX::Traits: 0.06
  MooseX::Types: 0.16
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_01
